### ISSUE TITLE
Sucede una excepcion

### ISSUE THREAD

**Issue by IDiegoUlises** [gsampallo/esp32cam-gdrive#1]
Delete issues

**Comment by IDiegoUlises** [comment]
Agrego que el modulo funciona correctamente para todas las tareas de programación y esta recien importado desde la fabrica

**Comment by gsampallo** [comment]
Hola, disculpa la demora en la respuesta. No se si ya lo pudiste resolver, si no es así consulto para tener mas info:
-Tenes conectado algo al modulo además del serial-usb al momento de iniciarlo? 
- Que versión de firmware tiene cargado?
- Probaste cargar el ejemplo blynk para ver que ocurre?

Saludos.

**Comment by IDiegoUlises** [comment]
lo unico que tengo conectado es el modulo Esp-32.
* Tiene la version de fabrica porque yo nunca le hecho ningun tipo de modificacion
* Tu segunda pregunta el modulo funciona correctamente con otras librerias y codigos 
Solo cuando uso la libreria de google drive sucede ese error  
saludos

**Comment by IDiegoUlises** [comment]
@gsampallo  you can delete issue?
